### ISSUE TITLE
Inquiry about Updates

### ISSUE THREAD

**Issue by WHUBaoZi** [RayShark0605/On_the_fly_SfM#1]
Hello RayShark. I am writing to express my appreciation for your work and to inquire about any potential future updates you might have planned. I noticed that the last update was four months ago, and I was wondering if you have plans to continue developing this project. Have a great day :)

**Comment by RayShark0605** [comment]
Hello, thank you for your interest in my repository. I will have a major update in the first half of this year!

**Comment by WHUBaoZi** [comment]
Thank you for the quick response and the exciting news! Looking forward to the update. Best wishes on the development!
